데이터: https://www.schoolinfo.go.kr/ng/go/pnnggo_a01_l2.do

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
path = '/Users/yniyunj/Desktop/교육공공데이터/데이터/002/'

df24 = pd.read_csv(path + '2024년도_전·출입 및 학업중단 학생 수(초)_전체.csv', encoding = 'utf-8')
df23 = pd.read_csv(path + '2023년도_전·출입 및 학업중단 학생 수(초)_전체.csv', encoding = 'utf-8')
df22 = pd.read_csv(path + '2022년도_전·출입 및 학업중단 학생 수(초)_전체.csv', encoding = 'utf-8')
df21 = pd.read_csv(path + '2021년도_전·출입 및 학업중단 학생 수(초)_전체.csv', encoding = 'utf-8')
df20 = pd.read_csv(path + '2020년도_전·출입 및 학업중단 학생 수(초)_전체.csv', encoding = 'utf-8')

In [4]:
df24

,시도교육청,교육지원청,지역,정보공시 학교코드,학교명,학교급코드,설립구분,제외여부,제외사유,1학년 전입학생수,...,4학년 전체학생수,5학년 전입학생수,5학년 전출학생수,5학년 전체학생수,6학년 전입학생수,6학년 전출학생수,6학년 전체 학생수,전입학생수(계),전출학생수(계),전체학생수(계)
0,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 서초구,S000003511,서울교육대학교부설초등학교,2,국립,N,NaN,5.0,...,104.0,2.0,1.0,108.0,1.0,1.0,110.0,31.0,12.0,610.0
1,서울특별시교육청,서울특별시중부교육지원청,서울특별시 종로구,S000003563,서울대학교사범대학부설초등학교,2,국립,N,NaN,1.0,...,106.0,3.0,2.0,105.0,2.0,0.0,100.0,23.0,15.0,595.0
2,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000737,서울개원초등학교,2,공립,N,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000738,서울개일초등학교,2,공립,N,NaN,4.0,...,181.0,10.0,13.0,183.0,26.0,8.0,176.0,88.0,63.0,1067.0
4,서울특별시교육청,서울특별시강남서초교육지원청,서울특별시 강남구,S010000739,서울개포초등학교,2,공립,N,NaN,26.0,...,121.0,135.0,0.0,111.0,106.0,0.0,79.0,695.0,5.0,649.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000801,월랑초등학교,2,공립,N,NaN,1.0,...,100.0,1.0,3.0,123.0,6.0,3.0,129.0,19.0,19.0,632.0
6298,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000834,이도초등학교,2,공립,N,NaN,3.0,...,186.0,3.0,4.0,228.0,3.0,6.0,190.0,30.0,28.0,1150.0
6299,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000836,도련초등학교,2,공립,N,NaN,9.0,...,201.0,2.0,6.0,210.0,1.0,6.0,196.0,26.0,46.0,1203.0
6300,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000837,삼화초등학교,2,공립,N,NaN,4.0,...,125.0,5.0,4.0,137.0,3.0,6.0,146.0,38.0,33.0,734.0
6301,제주특별자치도교육청,제주시교육지원청,제주특별자치도 제주시,S170000839,하귀일초등학교,2,공립,N,NaN,4.0,...,100.0,8.0,13.0,115.0,3.0,18.0,85.0,48.0,84.0,615.0

In [6]:
df24.columns

Index(['시도교육청', '교육지원청', '지역', '정보공시 학교코드', '학교명', '학교급코드', '설립구분', '제외여부',
       '제외사유', '1학년 전입학생수', '1학년 전출학생수', '1학년 전체학생수', '2학년 전입학생수', '2학년 전출학생수',
       '2학년 전체학생수', '3학년 전입학생수', '3학년 전출학생수', '3학년 전체학생수', '4학년 전입학생수',
       '4학년 전출학생수', '4학년 전체학생수', '5학년 전입학생수', '5학년 전출학생수', '5학년 전체학생수',
       '6학년 전입학생수', '6학년 전출학생수', '6학년 전체 학생수', '전입학생수(계)', '전출학생수(계)',
       '전체학생수(계)'],
      dtype='object')

In [7]:
drop_columns = ['시도교육청', '교육지원청', '정보공시 학교코드', '학교급코드', '제외여부', '제외사유']
df24.drop(drop_columns, axis=1)

,지역,학교명,설립구분,1학년 전입학생수,1학년 전출학생수,1학년 전체학생수,2학년 전입학생수,2학년 전출학생수,2학년 전체학생수,3학년 전입학생수,...,4학년 전체학생수,5학년 전입학생수,5학년 전출학생수,5학년 전체학생수,6학년 전입학생수,6학년 전출학생수,6학년 전체 학생수,전입학생수(계),전출학생수(계),전체학생수(계)
0,서울특별시 서초구,서울교육대학교부설초등학교,국립,5.0,2.0,96.0,5.0,1.0,96.0,7.0,...,104.0,2.0,1.0,108.0,1.0,1.0,110.0,31.0,12.0,610.0
1,서울특별시 종로구,서울대학교사범대학부설초등학교,국립,1.0,1.0,84.0,6.0,1.0,98.0,7.0,...,106.0,3.0,2.0,105.0,2.0,0.0,100.0,23.0,15.0,595.0
2,서울특별시 강남구,서울개원초등학교,공립,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,서울특별시 강남구,서울개일초등학교,공립,4.0,6.0,185.0,14.0,8.0,178.0,12.0,...,181.0,10.0,13.0,183.0,26.0,8.0,176.0,88.0,63.0,1067.0
4,서울특별시 강남구,서울개포초등학교,공립,26.0,1.0,132.0,117.0,2.0,87.0,158.0,...,121.0,135.0,0.0,111.0,106.0,0.0,79.0,695.0,5.0,649.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,제주특별자치도 제주시,월랑초등학교,공립,1.0,2.0,106.0,3.0,2.0,81.0,4.0,...,100.0,1.0,3.0,123.0,6.0,3.0,129.0,19.0,19.0,632.0
6298,제주특별자치도 제주시,이도초등학교,공립,3.0,2.0,162.0,9.0,7.0,200.0,5.0,...,186.0,3.0,4.0,228.0,3.0,6.0,190.0,30.0,28.0,1150.0
6299,제주특별자치도 제주시,도련초등학교,공립,9.0,4.0,179.0,1.0,12.0,200.0,6.0,...,201.0,2.0,6.0,210.0,1.0,6.0,196.0,26.0,46.0,1203.0
6300,제주특별자치도 제주시,삼화초등학교,공립,4.0,4.0,104.0,9.0,5.0,114.0,10.0,...,125.0,5.0,4.0,137.0,3.0,6.0,146.0,38.0,33.0,734.0
6301,제주특별자치도 제주시,하귀일초등학교,공립,4.0,11.0,109.0,14.0,8.0,105.0,6.0,...,100.0,8.0,13.0,115.0,3.0,18.0,85.0,48.0,84.0,615.0